### PR TITLE
Helidon SE

### PR DESCRIPTION
**Pull request by SentryMan**
Bog Standard Helidon SE with Oauth

### CODE REVIEW

**Comment by SentryMan** [comment]
@mraible ok, this is basically how an unaugmented Helidon SE app would look when generated by CLI.

**Comment by mraible** [comment]
@SentryMan I've created a new repo for the reactive version of each framework, and I've converted from Helidon MP to Helidon SE using this PR. You can see it in [this commit](https://github.com/oktadev/auth0-java-rest-api-reactive-examples/pull/1/commits/0fbd04971db13bc22ccb0ea05fa5896b22bbc913). 

The full PR to convert each framework to reactive is at https://github.com/oktadev/auth0-java-rest-api-reactive-examples/pull/1.

**Comment by mraible** [comment]
Hi @SentryMan,

Do you know how to modify this code to lazy-load the issuer and JWKS URI? The Helidon SE version is 5x slower to start than the Helidon MP version because MP lazy-loads the JWKS URI by default.

See https://github.com/oktadev/auth0-java-reactive-examples/issues/5 for more information.

**Comment by SentryMan** [comment]
I got nothing, never really handled JWT that much with helidon since an internal library takes care of the authentication for my applications.

**Comment by mraible** [comment]
@SentryMan I converted your example to use more configuration and less code in https://github.com/oktadev/auth0-java-reactive-examples/pull/6. I was unable to figure out how to configure everything in the `application.properties` file, that's why I'm using YAML. 

It still fails to startup when there's no internet connection, which means it'll take longer to start than the other frameworks.

**Pull request closed without merging**
