### PR TITLE
use AOT optimizations for Micronaut Example

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
can you update your readme instructions about how to create the app required?

**Comment by mraible** [comment]
@sdelamo I tried this PR again, and now it doesn't start successfully. 

```
$ build/native/nativeOptimizedCompile/app
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.9.3)

Exception in thread "main" java.lang.NoSuchMethodError: java.lang.invoke.MethodHandle.get()
	at com.example.rest.BeanDefinitionReferenceFactory.findAll(BeanDefinitionReferenceFactory.java:968)
	at io.micronaut.core.io.service.SoftServiceLoader$StaticServiceLoader.load(SoftServiceLoader.java:380)
	at io.micronaut.core.io.service.SoftServiceLoader$StaticServiceLoader.load(SoftServiceLoader.java:376)
	at io.micronaut.core.io.service.SoftServiceLoader.collectStaticServices(SoftServiceLoader.java:202)
	at io.micronaut.core.io.service.SoftServiceLoader.collectAll(SoftServiceLoader.java:172)
	at io.micronaut.context.DefaultBeanContext.resolveBeanDefinitionReferences(DefaultBeanContext.java:1753)
	at io.micronaut.context.DefaultApplicationContext.isBootstrapPropertySourceLocatorPresent(DefaultApplicationContext.java:157)
```

**Comment by sdelamo** [comment]
yup, investigating. Sorry for the nonie. I will make sure it passes and ping you again.

**Comment by sdelamo** [comment]
@mraible it should work now. It seems with have an issue with some optimisations, Java 17 and graalvm . We are investigating.  

By the way, with this changes: I am seeing 18ms startup time in MacBook Air M1 16GB.
```
./gradlew nativeOptimizedCompile  
./build/native/nativeOptimizedCompile/app
```

**Comment by mraible** [comment]
@sdelamo I tested your latest code and found the following startup times:

(20 + 25 + 18 + 29 + 27) / 5 = 23.8

If I test the non-optimized code, I see:

(24 + 34 + 31 + 21 + 33) / 5 = 28.6

**Comment by sdelamo** [comment]
do you test only startup time? You don't test time to first request? Would you be interested on contributing a script to test time to first request?

**Comment by mraible** [comment]
That's correct, I only tested startup time. I used the value (in milliseconds) printed by each framework.

I saw a talk from @alina-yur at Devoxx UK where she had some nice scripts for timing things. I asked her if they were available in a public repo. Her response:

> They aren't but I don't think they should be a secret. Let me talk to them, maybe we can publish them in a blog post.

If you have similar scripts, I'd love to use them!

**Comment by sdelamo** [comment]
We have this one, it is not scientific but I think it gives you an idea of the time to first response 

https://github.com/micronaut-projects/scripts/blob/main/ttfr.sh

**Comment by mraible** [comment]
@sdelamo I upgraded the Micronaut example to 4.0.3 in https://github.com/oktadev/auth0-java-rest-api-examples/pull/4. Are these changes still necessary for Micronaut 4?

**Comment by mraible** [comment]
FWIW, I updated the performance numbers using Micronaut 4 today. 

- [Startup](https://github.com/oktadev/auth0-java-rest-api-examples/commit/33df904e557dd02555526c265df08fae683edba8) - starts faster than Quarkus now!
- [Memory](https://github.com/oktadev/auth0-java-rest-api-examples/commit/3ffa832c5fe69246e936be7e4262ad68f69729b1) - consumes more initial memory, but less after requests

**Pull request closed without merging**
