### PR TITLE
Add reactive versions for each framework

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
@dalexandrov I'm trying to create reactive versions of this repo's resource server examples for Micronaut, Quarkus, Spring Boot, and Helidon. For Quarkus and Spring Boot, I only need to change one dependency to make it reactive. It doesn't seem that easy with Helidon. I know I can create a reactive Helidon application using the Helidon CLI:

```
helidon init --flavor SE --groupid com.okta.rest --artifactid helidon --package com.okta.rest --batch
```

If I look at the output of this command, the dependencies are all different compared to the existing MP example.

It seems like Helidon SE only [supports](https://helidon.io/docs/v3/#/se/security/providers) OIDC and not JWT (aka OAuth). Is that correct?

I'm just trying to create a resource server (an API that can be accessed via OAuth). I was able to do this with the other frameworks (and Helidon MP) without specifying a client ID or secret.

**Comment by dalexandrov** [comment]
> @dalexandrov I'm trying to create reactive versions of this repo's resource server examples for Micronaut, Quarkus, Spring Boot, and Helidon. For Quarkus and Spring Boot, I only need to change one dependency to make it reactive. It doesn't seem that easy with Helidon. I know I can create a reactive Helidon application using the Helidon CLI:
> 
> ```
> helidon init --flavor SE --groupid com.okta.rest --artifactid helidon --package com.okta.rest --batch
> ```
> 
> If I look at the output of this command, the dependencies are all different compared to the existing MP example.
> 
> It seems like Helidon SE only [supports](https://helidon.io/docs/v3/#/se/security/providers) OIDC and not JWT (aka OAuth). Is that correct?

Hello @mraible, sorry this mails somehow got to spam folder. Found them accidentally.
So, changing flavour does not mean you will get the same config. Helidon SE (unlike other frameworks) is quite different from Helidon MP. So, it is not just changing one dependency.

JWT is supported but no longer evolved.

**Comment by mraible** [comment]
@dalexandrov Do you have documentation on how to use JWT with Helidon SE?

**Comment by dalexandrov** [comment]
Yes, it is here: https://helidon.io/docs/v3/#/se/security/providers#JWT-Provider

I hope this example can help you: https://github.com/helidon-io/helidon/tree/helidon-3.x/examples/security/outbound-override

**Comment by mraible** [comment]
Closing because I created a new repo for the reactive versions. https://github.com/oktadev/auth0-java-reactive-examples

**Pull request closed without merging**
