### PR TITLE
Helidon SE (With Avaje DI and Code Gen)

### PR DESCRIPTION
**Pull request by SentryMan**
I only use SE normally, so curious how it compares. (I couldn't get the other helidon example working for me so I only tested this new module)

Uses [avaje](https://github.com/avaje) for DI and controller generation.

### CODE REVIEW

**Comment by mraible** [comment]
Thank you so much for this example! I need to figure out the best way to organize this repo to have classic and reactive versions. [This PR](https://github.com/oktadev/auth0-java-rest-api-examples/pull/8) has reactive versions for many frameworks, but it's on a branch, which makes it more difficult to discover.

**Comment by SentryMan** [comment]
helidon 4 might be hard to categorize since helidon has eviscerated all their reactive stuff and gone all in on virtual threads.

**Comment by mraible** [comment]
@SentryMan I'd prefer to use the Helidon SE version that most folks will use by default. For most of the other frameworks, that means the app that the CLI generates. Which of your two pull requests most closely matches that?

**Comment by SentryMan** [comment]
probably the other one

**Comment by SentryMan** [comment]
this may be how I do things, but helidon SE is pretty bare-bones when it comes to project generation

**Pull request closed without merging**
